start working
Ouriel91/monday-u-exercises pull request #9
Opened 2022-06-27 01:16 UTC by Ouriel91

2022-06-30 14:56 UTC, Ouriel91 commented
@shaneer @SergeiSafrigin

2022-07-07 12:44 UTC, SergeiSafrigin requested changes
Well done! See comments as we discussed in the live review

2022-07-07 12:44 UTC, SergeiSafrigin commented on README.md
> +nodemon server.js (prefer)
add code blocks

2022-07-07 12:44 UTC, SergeiSafrigin commented on README.md
> +Navigate to src/client and run
Product feedback:
- remove scroll from window,
- chart change colors to better suit the apps' color scheme
- try to improve the tabs UI (also in a non-standard place)
- filter toggle

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/App.css
> +    transform: translate(-50%, -50%);
please center using flex (add a wrapper component [nav-bar?])

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/App.jsx
> +  const navigate = useNavigate();
big like!

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/App.test.js
> +  expect(linkElement).toBeInTheDocument();
could be very cool to add a test file for the todo component as well

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/Bottom/Bottom.jsx
> +function Bottom({length = 0, deleteTodo}) {
consider renaming to footer

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/Bottom/Bottom.jsx
> +function Bottom({length = 0, deleteTodo}) {
rename the length variable as well to be more descriptive

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/ClearAll/ClearAll.jsx
> +import styles from './ClearAll.module.css'
rename folders to snake case

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/ClearAll/ClearAll.jsx
> +    <button
consider moving the button to it's own component and act as a base button in ur app

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/ClearAll/ClearAll.jsx
> +    <button
Then rename this component to ClearAllButton

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/ClearAll/ClearAll.jsx
> +      className={[anotherStyles.button, styles.clearAllButton, length > 0 ? styles.active : ""].join(' ')}
use classnames 3rd party library

ex:
classnames("my-class", null, undefined, " some-class  ", {
    'is-open': isOpen
})

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/ClearAll/ClearAll.jsx
> +      onClick={() => deleteTodo('delete-all')}>
extract to a variable and wrap with useCallback

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/ClearAll/ClearAll.module.css
> +    opacity: 1;
do we really need it here? are you overriding a default?

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/ClearAll/ClearAll.module.css
> +    cursor: pointer;
also should be part of the base

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Bottom Level/SumTodos/SumTodos.jsx
> +function SumTodos({length = 0}) {
consider removing this component and just use the span in the parent component

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Container.jsx
> +    } = useContainer();
react docs states that you should rarely use custom hooks, mostly when they are very reusable

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Container.jsx
> +    } = useContainer();
Well done on using a custom hook! 💪

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Container.jsx
> +            <Top getTodos={getTodos}/>
consider renaming to Header rather than Top

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Container.jsx
> +            {loader ? <Loader /> : null}
isLoading

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Container.jsx
> +            <Input addTodo={addTodo}/>
rename to TodoInput

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Container.jsx
> +                <EmptyTodosShow />
consider moving the placeholder logic inside the TodoList

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Main Level/TodoList/TodoList.jsx
> +      {renderItems}
`todos.map{todo = <Todo todo={todo}} />`

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Main Level/TodoList/TodoList.jsx
> +  const {renderItems} = useTodoList(todos, deleteTodo, editTodo)
same as the container hook

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/Main Level/TodoList/TodoList.module.css
> +    padding: 0;
consider using a custom scoller UI, it will boost the look of your app.
Using if with mixing could be amazing as you could easily reuse them across the app.
(read more on mixins)

2022-07-07 12:44 UTC, SergeiSafrigin commented on src/client/src/components/App/Container/useContainer.jsx
> +        if(deletedItem.id) {
please encapsulate all the logic implementation, and move it to helper functions and service classes to improve readability and re-usability (and even maintenance)

2022-07-11 08:10 UTC, merged